# Generated by Django 4.0.4 on 2022-05-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandes', models.CharField(blank=True, default='ali', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='color',
            name='colores',
            field=models.CharField(blank=True, default='ali', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
            preserve_default=False,
        ),
    ]
